'''
Given a list of x names (original_names)
Given a list of x+n alternatives (new_names)
I want to iterate over the list of original_names and replace them with a new name


Purpose of this file
	iterate over the list of original_names and replace them with a new name
	
'''

original_names = ['name":"Karen Dove"}',
'{name:"Christine Nguyen"}',
'{name:"Grace Paduano"}',
'{name:"Melissa-Marie Cormier"}',
'{name:"Jennifer Calegoure"}',
'{name:"Michelle Vachon-Wilson"}',
'{name:"Marie Josée Lemieux"}',
'{name:"Isabelle Renaud"}',
'{name:"Caroline Godard"}',
'{name:"Grace Paduano , Melissa-Marie Cormier?"}',
'{name:"Christine Racicot"}',
'{name:"Sarah St-Germain & Cynthia Vokey"}',
'{name:"Jocelyne Larocque"}',
'{name:"Carole Fuoco"}',
'{name:"Jean Cardinal"}',
'{name:"Mélodie Blais"}',
'{name:"Marie-Josée Lemieux"}',
'{name:"Rachelle Dempster"}',
'{name:"Sarah St-Germain"}',
'{name:"TBD"}',
'{name:"Lyne Cyr"}',
'{name:"Mélissa-Marie Cormier"}',
'{name:"Doris  Gobeil / Serge Demers"}',
'{name:"Miguel Fernandez"}',
'{name:"Lisa Brooks"}',
'{name:"Nathalie Laviades-Jodouin "}',
'{name:"John Medcof"}',
'{name:"Doris Gobeil"}',
'{name:""}',
'{name:"Robert Beaumier"}',
'{name:"Marie-Josée Lemieux / Lyne Cyr"}',
'{name:"Pierre Marquis"}',
'{name:"Guy Filteau"}',
'{name:"Sheryne Morcos"}',
'{name:"Melissa Bennard"}',
'{name:"Cara Vandale"}',
'{name:"Louise Jasmin"}',
'{name:"Karen Dove / Lisa Harris"}',
'{name:"Edith Lacroix"}',
'{name:"Jean Gallagher"}']

new_names=['Ivey Sigala',
'Kelsie Yochum',
'Mose Viars',
'Carolynn Largent',
'Angle Vossler',
'Marilee Reinert',
'Aleen Bangert',
'Lakenya Raminez',
'Alaine Bettinger',
'Romana Hyppolite',
'Alejandrina Isham',
'Chandra Tutino',
'Wendi Savidge',
'Celestine Emory',
'Terence Baley',
'Ashely Dawkins',
'Marg Sequeira',
'Saran Hartin',
'Martine Alcantar',
'Pamella Mach',
'Jovita Bledsoe',
'Birgit Devries',
'Marcene Griffy',
'Malcolm Presgraves',
'Lisha Distefano',
'Dusti Welsh',
'Maryjane Lilienthal',
'Khalilah Medina',
'Elia Lebrun',
'Tai Ikeda',
'Kathe Rudisill',
'Paula Leone',
'Remona Lint',
'Claudine Sherron',
'Aaron Rocco',
'Myrtie Zeiler',
'Mila Kennard',
'Brandi Fairfield',
'Lourdes Mahmood',
'Kesha An',
'Rosalva Wattenbarger',
'Emelda Holaway',
'Rosann Trexler',
'Hermina Beggs',
'Darron Ohlinger',
'Jayna Dutremble',
'Velma Ray',
'Shauna Cowens',
'Elza Swain',
'Saturnina Byrom']

x = 0
for old, new in zip(original_names, new_names):
	print("MATCH (p:Person" + old + ") SET p.name='" + new + "';")
